[tool.poetry]
name = "api_to_s3"
version = "0.1.0"
description = ""
authors = ["ryanjclark <ryanclark2021@u.northwestern.edu>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
